In [1]:
import numpy as np

In [4]:
X = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
])
from sklearn.decomposition import NMF
model = NMF(n_components=4, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_

In [5]:
print("Matrix W")
print(W)
print("Matrix H")
print(H)

Matrix W
[[  2.54138865e-01   2.18987773e+00   0.00000000e+00   1.08403239e+00]
 [  2.21493346e-02   0.00000000e+00   0.00000000e+00   2.24063058e+00]
 [  2.35553275e+00   7.18358583e-01   1.02079516e-03   0.00000000e+00]
 [  1.77247213e+00   0.00000000e+00   0.00000000e+00   5.60159674e-01]
 [  1.26457516e-01   0.00000000e+00   4.65769783e+00   6.72250655e-10]]
Matrix H
[[  0.00000000e+00   4.15145184e-03   0.00000000e+00   2.12231320e+00]
 [  1.39878684e+00   1.37030168e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.14585894e-01   1.07349166e+00   8.01172098e-01]
 [  1.78547796e+00   0.00000000e+00   2.48027294e-17   4.25253062e-01]]
